# Generated by Django 3.2.3 on 2021-07-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Queries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Description', models.TextField(max_length=400)),
                ('EmailID', models.CharField(max_length=50)),
            ],
        ),
    ]
